media:
  input: static/images
  output: /images
content:
  - name: work
    label: Work
    type: collection
    path: 'content/work'
    filename: '{primary}.md'
    view:
      fields: [ title ]
    fields:
      - name: cover-image
        label: Cover Image
        type: image
        description: Image used on home page post list, 1920x1080
      - name: title
        label: Title
        type: string
      - name: hero-desktop
        label: Hero Desktop Image
        type: image
        description: Image used for post hero (desktop), 1920x1080
      - name: hero-mobile
        label: Hero Mobile Image
        type: image
        description: Image used for post hero (mobile), 480x853
      - name: opening-title
        label: Opening Title
        type: string
      - name: opening-copy
        label: Opening Copy
        type: string
      - name: role
        label: Role
        type: string
      - name: role-team
        label: Team
        type: string
        list: 
          min: 1
          max: 10
      - name: role-me
        label: My Role
        type: string
        list: 
          min: 1
          max: 10
      - name: body
        label: Body
        type: rich-text