media:
  input: static/images
  output: /images
content:
  - name: work
    label: Work
    type: collection
    path: 'content/work'
    filename: '{primary}.md'
    view:
      fields: [ title ]
    fields:
      - name: cover
        label: Cover Image
        type: image
        description: Image used for home page Case Studies, 800x600px
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text