media:
  input: static/images
  output: /images
content:
  - name: work
    label: Work
    type: collection
    path: 'content/work'
    filename: '{primary}.md'
    view:
      fields: [ title ]
    fields:
      - name: cover-image
        label: Cover Image
        type: image
        description: Image used on home page post list, 1920x1080
      - name: title
        label: Title
        type: string
      - name: hero-1-desktop
        label: Hero Desktop Image
        type: image
        description: Image used for post hero (desktop), 1920x1080
      - name: hero-1-mobile
        label: Hero Mobile Image
        type: image
        description: Image used for post hero (mobile), 480x853
      - name: opening-title
        label: Opening Title
        type: string
      - name: opening-copy
        label: Opening Copy
        type: string
      - name: role
        label: Team + Role
        type: string
      - name: role-team
        label: Team
        type: string
        list: 
          min: 1
          max: 10
      - name: role-me
        label: My Role
        type: string
        list: 
          min: 1
          max: 10
      - name: role-opportunity
        label: Challenge + Opportunity
        type: string
        list: 
          min: 1
          max: 10
      - name: role-leadership
        label: Leadership Highlight
        type: string
      - name: impact-1-title
        label: Impact Title 1
        type: string
      - name: impact-1-copy
        label: Impact Copy 1
        type: string
      - name: impact-2-title
        label: Impact Title 2
        type: string
      - name: impact-2-copy
        label: Impact Copy 2
        type: string
      - name: impact-3-title
        label: Impact Title 3
        type: string
      - name: impact-3-copy
        label: Impact Copy 3
        type: string
      - name: 2-card-section-title
        label: Section Title
        type: string
      - name: 2-card-section-copy
        label: Section Copy
        type: string
      - name: hero-2-desktop
        label: Hero Desktop Image
        type: image
        description: Image used for post hero (desktop), 1920x1080
      - name: hero-2-mobile
        label: Hero Mobile Image
        type: image
        description: Image used for post hero (mobile), 480x853
      - name: body
        label: Body
        type: rich-text