media:
  input: static/images
  output: /assets/images/
content:
  - name: work
    label: Work
    type: collection
    path: 'content/work'
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text