media:
  input: static/images
  output: /images
content:
  - name: work
    label: Work
    type: collection
    path: 'content/work'
    filename: '{primary}.md'
    view:
      fields: [ title, role ]
    fields:
      - name: cover
        label: Cover Image
        type: image
        description: Image used for home page Case Studies, 16:9 ratio
      - name: title
        label: Title
        type: string
      - name: role
        label: Role
        type: string
      - name: team
        label: Team
        type: string
        list: 
          min: 1
          max: 10
      - name: body
        label: Body
        type: rich-text